// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Andrea Genovese

/**
 * The MCP tools Recordare serves (name, title, description, JSON Schema of the arguments), for connectors that must
 * declare tools before talking to the service. Generated by the conformance suite (service/test/conformance,
 * RECORDARE_UPDATE_TOOLS=1), which fails when this copy drifts from the service.
 */
export const TOOLS = [
  {
    "name": "correct_episode",
    "title": "Correct a memory",
    "description": "The user corrects a remembered episode (wrong date or detail). The old version is kept as history, never shown as current.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        },
        "content": {
          "type": "string"
        },
        "occurred_at": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}(-\\d{2})?$"
        },
        "date_precision": {
          "type": "string",
          "enum": [
            "day",
            "month",
            "year",
            "approximate"
          ]
        }
      },
      "required": [
        "id"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  {
    "name": "forget_episode",
    "title": "Forget a memory",
    "description": "The user asks to forget an episode. It is deleted with its corrections and never recreated.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        }
      },
      "required": [
        "id"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  {
    "name": "log_episode",
    "title": "Note something that happened or is planned",
    "description": "Explicit capture (\"note that today I serviced the car\"). Resolve the date yourself (ISO).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "event",
            "plan"
          ]
        },
        "occurred_at": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}(-\\d{2})?$"
        },
        "occurred_until": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}(-\\d{2})?$"
        },
        "date_precision": {
          "type": "string",
          "enum": [
            "day",
            "month",
            "year",
            "approximate"
          ]
        },
        "people": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "place": {
          "type": "string"
        }
      },
      "required": [
        "content"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  {
    "name": "remember",
    "title": "Remember something about the user",
    "description": "Explicit \"remember that…\" about preferences, habits, values, knowledge.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "category": {
          "type": "string",
          "enum": [
            "preference",
            "habit",
            "value",
            "relationship",
            "knowledge",
            "profile",
            "constraint"
          ]
        }
      },
      "required": [
        "content"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  {
    "name": "resolve_period",
    "title": "Turn a period expression into dates",
    "description": "Deterministic: \"questa settimana\", \"la settimana scorsa\", \"a febbraio\", \"lo scorso dicembre\", \"last week\"… → {from, to} (ISO, inclusive).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "expression": {
          "type": "string"
        }
      },
      "required": [
        "expression"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  {
    "name": "search_episodes",
    "title": "Search what happened",
    "description": "Search what the user lived, did or planned (events, plans, changes), with dates and status. Use `from`/`to` (ISO dates, inclusive; see resolve_period) for questions about a period. mode: \"search\" = most relevant, \"list\" = chronological in the period (overviews, counting), \"latest\" = most recent first (\"when did I last…\").",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "description": "What to look for — pass the user's question also when listing a period: it ranks the items and finds the matching chat excerpts",
          "type": "string"
        },
        "from": {
          "description": "Start date, ISO (YYYY-MM-DD or YYYY-MM)",
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}(-\\d{2})?$"
        },
        "to": {
          "description": "End date, ISO (YYYY-MM-DD or YYYY-MM), inclusive",
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}(-\\d{2})?$"
        },
        "mode": {
          "type": "string",
          "enum": [
            "search",
            "list",
            "latest"
          ]
        },
        "include_plans": {
          "type": "boolean"
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 50
        }
      },
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  {
    "name": "search_memory",
    "title": "Search who the user is",
    "description": "Search preferences, habits, values, relationships, knowledge and current state (car, home, job…). Use `as_of` (ISO date) for \"what was it on that date\" questions; each fact comes with its history.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Topic"
        },
        "as_of": {
          "description": "ISO date (YYYY-MM-DD); default today",
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}(-\\d{2})?$"
        },
        "include_pending": {
          "type": "boolean"
        }
      },
      "required": [
        "query"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  }
] as const;
